syntax = "proto3";

package appointment;

service AppointmentService {
 rpc CreateSchedule (CreateScheduleRequest) returns (ScheduleResponse);
rpc GetAvailableSlots (GetSlotsRequest) returns (GetSlotsReply);
rpc BookSlot (BookSlotRequest) returns (AppointmentResponse);

}

message CreateScheduleRequest {
  string doctorId = 1;
  string date = 2; // yyyy-MM-dd
}

message ScheduleResponse {
  string scheduleId = 1;
  string status = 2;
}
message AppointmentResponse {
  string appointmentId = 1;
  string status = 2;
}
message GetSlotsRequest {
  string doctorId = 1;
  string date = 2;
}

message TimeSlotReply {
  string slotId = 1;
  string startTime = 2;
  string endTime = 3;
  bool isBooked = 4;
}

message GetSlotsReply {
  repeated TimeSlotReply slots = 1;
}

message BookSlotRequest {
  string slotId = 1;
  string patientId = 2;
}